### ISSUE TITLE
Possible access issue

### ISSUE THREAD

**Issue by mchurchward** [EEXCESS/MoodleServerPlugin#10]
Hi. Looking at "delete_imglic_from_DB.php" and delete_interests_from_DB.php", it is possible for users to delete records created by other users by accessing the URL's of these scripts directly. I believe those scripts were intended to be used by a user to delete their own entries only, but the delete script does not check to see if the record was entered by the user accessing it.
All any valid user on the site needs to do is look up their own sesskey value, which can be done by looking at the source code of the page, and enter a URL such as:
http://[moodlesite]/blocks/eexcess/delete_interests_from_DB.php?catid=5&sesskey=3NvZfzAwBd
and they will have deleted the record with "id=5", even if that was not one of theirs.
I believe you need to ensure that the record also contains the userid of the user accessing it?

**Comment by mudrd8mz** [comment]
This seems to be relevant to previously reported issue https://github.com/EEXCESS/moodle-block_eexcess/issues/4
