### ISSUE TITLE
lib.php should only contain functions

### ISSUE THREAD

**Issue by danmarsden** [EEXCESS/MoodleServerPlugin#2]
lib.php should only contain functions, it is called from many core areas of Moodle - this logic should be moved somewhere else:
https://github.com/EEXCESS/MoodleServerPlugin/blob/master/lib.php#L27

**Comment by megamuf** [comment]
Hello,

I have a question,
" this logic should be moved somewhere else:
https://github.com/EEXCESS/MoodleServerPlugin/blob/master/lib.php#L27"
only L27?
or all of this?
https://github.com/EEXCESS/MoodleServerPlugin/blob/master/lib.php#L27-L38

Basically i would like to know is logic for requiring javascript can remain in lib.php, because I need it to run in all pages.

Thank you in advance.

**Comment by danmarsden** [comment]
the full block should be removed - lib.php should really only contain functions and you should find another way to add the javascript to the header. I'd suggest creating a post in the moodle community general developer forum describing what you are trying to do and see if others have good suggestions on  a better way to do it. You may find that changing to use a different type of plugin might provide an easier solution. I haven't got a great understanding on what your plugin does but I wonder if a better plugin type might be "filter" ? - that way it could also be turned on/off for different courses/plugins etc - it also provides hooks that would allow adding javascript etc.

I do not personally make the final call on if this will be a blocker for approval in the plugins database but it definitely does not follow Moodle coding guidelines.

**Comment by mudrd8mz** [comment]
Dan is right in that the body of lib.php must not do these things. The lib.php of many plugins are included during the bootstrap and could be executed any time by accidents (including CLI scripts execution, handling a web service request etc).

Unfortunately Moodle does not provide a unified and clean hooking mechanism for these things (at least I am not aware of any). Maybe in this particular case, the `$PAGE->requires->js_call_amd()` could be done as a part of `local_eexcess_extend_navigation()`? Would it help?

**Comment by mudrd8mz** [comment]
By the way, this is a blocker at the moment. If you tried to install the plugin from scratch, you would notice it immediately kills the site with:

```
 Table "local_eexcess_interests" does not exist
Debug info:
Error code: ddltablenotexist
Stack trace:

    line 590 of /lib/dml/moodle_database.php: dml_exception thrown
    line 1259 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
    line 29 of /local/eexcess/lib.php: call to moodle_database->get_records()
    line 893 of /lib/classes/component.php: call to include_once()
    line 1299 of /lib/navigationlib.php: call to core_component::get_plugin_list_with_file()
    line 222 of /blocks/navigation/block_navigation.php: call to global_navigation->initialise()
    line 178 of /blocks/navigation/block_navigation.php: call to block_navigation->get_navigation()
    line 288 of /blocks/moodleblock.class.php: call to block_navigation->get_content()
    line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
    line 973 of /lib/blocklib.php: call to block_base->get_content_for_output()
    line 1025 of /lib/blocklib.php: call to block_manager->create_block_contents()
    line 474 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
    line 39 of /theme/bootstrapbase/renderers/core_renderer.php: call to core_renderer->standard_head_html()
    line 52 of /theme/clean/layout/columns3.php: call to theme_bootstrapbase_core_renderer->standard_head_html()
    line 1016 of /lib/outputrenderers.php: call to include()
    line 946 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 112 of /index.php: call to core_renderer->header()
```

which is a result of attempting to do things in lib.php this way.

**Comment by megamuf** [comment]
Hello David,
Thanks for your reply,
I installed the plugin on a clean version of Moodle I did not have this problem.
![eexcess installation](https://cloud.githubusercontent.com/assets/13167613/12850131/2dc41070-cc1b-11e5-928d-9bd49534d5e3.png)

Also I placed $ PAGE-> requires-> js_call_amd () in local_eexcess_extend_navigation ()
