### ISSUE TITLE
direct access to $_GET/$_POST variables is not allowed

### ISSUE THREAD

**Issue by danmarsden** [EEXCESS/MoodleServerPlugin#3]
there seems to be a few examples of this in your code:
https://github.com/EEXCESS/MoodleServerPlugin/blob/master/eexcess_options.php#L39

these should be converted to using optional/required_param function calls as per Moodle coding and security guidelines.

**Comment by mudrd8mz** [comment]
Please note it would help if the reported issues were referenced from the commit messages so that we know if and how they were addressed.
