### ISSUE TITLE
login and capability checks need to be added

### ISSUE THREAD

**Issue by danmarsden** [EEXCESS/MoodleServerPlugin#4]
this page:
https://github.com/EEXCESS/MoodleServerPlugin/blob/master/delete_from_DB.php

allows data to be deleted from the db without requiring authentication or capability checks - in conjunction with using raw $_POST this is very dangerous. I would advise you spend some time upskilling yourself on general PHP security guidelines - We have the following in Moodle docs
https://docs.moodle.org/dev/Security
but for general PHP stuff OWASP has some good resources here:
https://www.owasp.org/index.php/PHP_Security_Cheat_Sheet

**Comment by mudrd8mz** [comment]
The script is still vulnerable to cross site request forgery (https://en.wikipedia.org/wiki/Cross-site_request_forgery), e.g. via a forum post containing

```
<img src=".../local/eexcess/delete_from_DB.php?id=1" height="1" width="1" alt="" />
```

Please read more on sesskey mechanism. By the way, is this supposed to be a handler of a AJAX request or what?

**Comment by megamuf** [comment]
Yes, this supposed to be a handler of a AJAX request.

**Comment by mudrd8mz** [comment]
> Yes, this supposed to be a handler of a AJAX request.

Well, in this case you should be interested in https://docs.moodle.org/dev/AJAX_pre_2.9 and https://docs.moodle.org/dev/AJAX - most notably the usage of the `AJAX_SCRIPT` constant.

**Comment by megamuf** [comment]
> Well, in this case you should be interested in https://docs.moodle.org/dev/AJAX_pre_2.9 and https://docs.moodle.org/dev/AJAX - most notably the usage of the AJAX_SCRIPT constant.

it is necessary to use?
