### ISSUE TITLE
hard coded strings

### ISSUE THREAD

**Issue by danmarsden** [EEXCESS/MoodleServerPlugin#5]
there seems to be some hard-coded strings in the code - you should convert these to strings inside the language file.
https://github.com/EEXCESS/MoodleServerPlugin/blob/master/user_settings_form.php#L67

**Comment by mudrd8mz** [comment]
Again, knowing what was changed with regards to this issue would help - please see e.g. the section on "Commits + Issues" at https://github.com/blog/831-issues-2-0-the-next-generation
