### ISSUE TITLE
Plugins guardians review comments

### ISSUE THREAD

**Issue by mchurchward** [EEXCESS/MoodleServerPlugin#9]
Hi.
I have started looking at your block, and have some initial issues and questions.
1) Since this is a Moodle block, you should name the repository with the Moodle frankenstyle naming. So the block would be called "moodle-block_eexcess". This helps the plugins database and automates scripts.
2) The "readme" mentions an associated atto plugin. I don't see that submitted to the plugins database. You should submit that as well as another plugin. You can also submit a "set" that includes both plugins together for reference (see https://moodle.org/plugins/browse.php?list=set&id=7 for an example of a set).
3) I see you previously had submitted a local plugin (https://moodle.org/plugins/local_eexcess). I believe this block replaces that? If so, can you confirm so we can remove that submission?

Thanks!

**Comment by megamuf** [comment]
Hello Mike,
thanks for your answer!
1) Repository renamed. 
2) Soon I will also add atto plugin.
3) Yes it can be removed.
